import { create } from 'zustand';

const OUTLETS = {
  all: 'All Outlets (Global)',
  'outlet-1': 'Koramangala Branch',
  'outlet-2': 'Indiranagar Branch',
  'outlet-3': 'HSR Layout Branch',
};

const INGREDIENTS_MASTER = [
  { id: 'ING-001', name: 'Premium Flour',       category: 'Dry Goods',    unit: 'kg',     costPerUnit: 1.20, minStock: 50,  reorderQty: 100, vendorId: 'V-001' },
  { id: 'ING-002', name: 'Mozzarella Cheese',   category: 'Dairy',        unit: 'kg',     costPerUnit: 8.50, minStock: 20,  reorderQty: 40,  vendorId: 'V-002' },
  { id: 'ING-003', name: 'Tomato Paste',        category: 'Canned Goods', unit: 'liters', costPerUnit: 3.40, minStock: 15,  reorderQty: 30,  vendorId: 'V-001' },
  { id: 'ING-004', name: 'Pizza Boxes (Large)', category: 'Packaging',    unit: 'pieces', costPerUnit: 0.45, minStock: 500, reorderQty: 1000,vendorId: 'V-003' },
  { id: 'ING-005', name: 'Chicken',             category: 'Meat',         unit: 'kg',     costPerUnit: 6.00, minStock: 30,  reorderQty: 60,  vendorId: 'V-002' },
];

const initialVendors = [
  { id: 'V-001', name: 'AgroFresh Supplies',   contact: '+91 98765 00001', email: 'agro@fresh.com',    category: 'Dry Goods & Canned', leadTime: 2, paymentTerms: 'Net 30', active: true  },
  { id: 'V-002', name: 'Prime Dairy & Meats',  contact: '+91 98765 00002', email: 'prime@dairy.com',   category: 'Dairy & Meat',       leadTime: 1, paymentTerms: 'COD',    active: true  },
  { id: 'V-003', name: 'PackRight Solutions',  contact: '+91 98765 00003', email: 'info@packright.com',category: 'Packaging',          leadTime: 3, paymentTerms: 'Net 15', active: true  },
];

const initialStockLevels = {
  'outlet-1': { 'ING-001': 45, 'ING-002': 12, 'ING-003': 28, 'ING-004': 350, 'ING-005': 18 },
  'outlet-2': { 'ING-001': 80, 'ING-002': 30, 'ING-003': 20, 'ING-004': 700, 'ING-005': 25 },
  'outlet-3': { 'ING-001': 60, 'ING-002': 22, 'ING-003': 12, 'ING-004': 420, 'ING-005': 35 },
};

const now = Date.now();
const daysAgo = (n) => new Date(now - n * 86400000).toISOString();

const initialTransactions = [
  { id: 'TXN-001', date: daysAgo(5), type: 'stock_in',  reason: 'purchase',     ingredientId: 'ING-001', outletId: 'outlet-1', qty: 100, note: 'Weekly purchase',    poRef: 'PO-001', balance: 145, costPerUnit: 1.20 },
  { id: 'TXN-002', date: daysAgo(5), type: 'stock_out', reason: 'consumption',  ingredientId: 'ING-001', outletId: 'outlet-1', qty: 55,  note: 'Daily consumption',  poRef: null,     balance: 90,  costPerUnit: 1.20 },
  { id: 'TXN-003', date: daysAgo(4), type: 'stock_out', reason: 'wastage',      ingredientId: 'ING-001', outletId: 'outlet-1', qty: 45,  note: 'Expired stock',      poRef: null,     balance: 45,  costPerUnit: 1.20 },
  { id: 'TXN-004', date: daysAgo(3), type: 'stock_in',  reason: 'purchase',     ingredientId: 'ING-002', outletId: 'outlet-1', qty: 30,  note: 'Emergency restock',  poRef: 'PO-002', balance: 42,  costPerUnit: 8.50 },
  { id: 'TXN-005', date: daysAgo(3), type: 'stock_out', reason: 'consumption',  ingredientId: 'ING-002', outletId: 'outlet-1', qty: 18,  note: 'Daily consumption',  poRef: null,     balance: 24,  costPerUnit: 8.50 },
  { id: 'TXN-006', date: daysAgo(2), type: 'stock_out', reason: 'damage',       ingredientId: 'ING-002', outletId: 'outlet-1', qty: 12,  note: 'Packaging damaged',  poRef: null,     balance: 12,  costPerUnit: 8.50 },
  { id: 'TXN-007', date: daysAgo(1), type: 'stock_in',  reason: 'purchase',     ingredientId: 'ING-005', outletId: 'outlet-2', qty: 40,  note: 'Vendor delivery',    poRef: 'PO-003', balance: 65,  costPerUnit: 6.00 },
  { id: 'TXN-008', date: daysAgo(1), type: 'stock_out', reason: 'consumption',  ingredientId: 'ING-005', outletId: 'outlet-2', qty: 40,  note: 'Daily consumption',  poRef: null,     balance: 25,  costPerUnit: 6.00 },
  { id: 'TXN-009', date: daysAgo(0), type: 'stock_in',  reason: 'purchase',     ingredientId: 'ING-003', outletId: 'outlet-3', qty: 20,  note: 'New day stock',      poRef: 'PO-004', balance: 32,  costPerUnit: 3.40 },
  { id: 'TXN-010', date: daysAgo(0), type: 'stock_out', reason: 'wastage',      ingredientId: 'ING-003', outletId: 'outlet-3', qty: 8,   note: 'Spoiled overnight',  poRef: null,     balance: 24,  costPerUnit: 3.40 },
];

const initialPOs = [
  { id: 'PO-001', date: daysAgo(5), outletId: 'outlet-1', vendorId: 'V-001', status: 'Received',     isAutoGenerated: false, items: [{ ingredientId: 'ING-001', qty: 100, costPerUnit: 1.20 }], totalCost: 120.00 },
  { id: 'PO-002', date: daysAgo(3), outletId: 'outlet-1', vendorId: 'V-002', status: 'Received',     isAutoGenerated: false, items: [{ ingredientId: 'ING-002', qty: 30,  costPerUnit: 8.50 }], totalCost: 255.00 },
  { id: 'PO-003', date: daysAgo(1), outletId: 'outlet-2', vendorId: 'V-002', status: 'Received',     isAutoGenerated: false, items: [{ ingredientId: 'ING-005', qty: 40,  costPerUnit: 6.00 }], totalCost: 240.00 },
  { id: 'PO-004', date: daysAgo(0), outletId: 'outlet-3', vendorId: 'V-001', status: 'Pending',      isAutoGenerated: true,  items: [{ ingredientId: 'ING-003', qty: 20,  costPerUnit: 3.40 }], totalCost: 68.00  },
  { id: 'PO-005', date: daysAgo(0), outletId: 'outlet-2', vendorId: 'V-003', status: 'Ordered',      isAutoGenerated: false, items: [{ ingredientId: 'ING-004', qty: 500, costPerUnit: 0.45 }], totalCost: 225.00 },
];

let _txnCounter = 10;
const txnId = () => `TXN-${String(++_txnCounter).padStart(3, '0')}`;
let _poCounter = 5;
const poId  = () => `PO-${String(++_poCounter).padStart(3, '0')}`;
let _vCounter = 3;
const vId   = () => `V-${String(++_vCounter).padStart(3, '0')}`;

const computeAllOutlets = (stockLevels) => {
  const combined = {};
  Object.values(stockLevels).forEach((outletStock) => {
    Object.entries(outletStock).forEach(([ingId, qty]) => {
      combined[ingId] = (combined[ingId] || 0) + qty;
    });
  });
  return combined;
};

export const useInventoryStore = create((set, get) => ({
  // ── Async Meta (non-breaking) — wire to UI spinners/toasts when API is live ──
  loading: {},   // { fetchIngredients: true, addStockIn: false, ... }
  errors:  {},   // { addStockIn: 'Invalid quantity', ... }
  _setLoading: (key, val) => set((s) => ({ loading: { ...s.loading, [key]: val } })),
  _setError:   (key, err) => set((s) => ({ errors:  { ...s.errors,  [key]: err  } })),
  _clearError: (key)      => set((s) => ({ errors:  { ...s.errors,  [key]: null } })),

  // ── Pagination / Filter State (ready for backend paging) ─────────────────
  transactionFilters: {
    outletId:     'outlet-1',
    ingredientId: null,
    dateFrom:     null,
    dateTo:       null,
    type:         null,   // 'stock_in' | 'stock_out'
    page:         1,
    pageSize:     20,
    total:        0,
  },
  setTransactionFilters: (filters) => set((s) => ({
    transactionFilters: { ...s.transactionFilters, ...filters }
  })),

  // ── UI ────────────────────────────────────────────────────
  activeTab: 'ingredients',
  setActiveTab: (tab) => set({ activeTab: tab }),
  selectedOutlet: 'outlet-1',
  setSelectedOutlet: (id) => set({ selectedOutlet: id }),

  // ── Master Data ───────────────────────────────────────────
  OUTLETS,
  ingredients: INGREDIENTS_MASTER,
  addIngredient: (data) => set((s) => ({
    ingredients: [...s.ingredients, {
      id: `ING-${String(s.ingredients.length + 1).padStart(3, '0')}`,
      reorderQty: data.minStock * 2,
      vendorId: null,
      ...data,
    }]
  })),
  updateIngredient: (id, data) => set((s) => ({
    ingredients: s.ingredients.map((i) => i.id === id ? { ...i, ...data } : i)
  })),

  // ── Vendors ───────────────────────────────────────────────
  vendors: initialVendors,
  addVendor: (data) => set((s) => ({
    vendors: [...s.vendors, { id: vId(), active: true, ...data }]
  })),
  updateVendor: (id, data) => set((s) => ({
    vendors: s.vendors.map((v) => v.id === id ? { ...v, ...data } : v)
  })),
  deleteVendor: (id) => set((s) => ({
    vendors: s.vendors.filter((v) => v.id !== id)
  })),

  // ── Stock Levels ──────────────────────────────────────────
  stockLevels: initialStockLevels,
  getStock: (outletId) => {
    const { stockLevels } = get();
    if (outletId === 'all') return computeAllOutlets(stockLevels);
    return stockLevels[outletId] || {};
  },

  // Single Stock In (accumulates on top of remaining)
  addStockIn: (ingredientId, qty, outletId, note = '', reason = 'purchase', poRef = null) => {
    const parsed = parseFloat(qty);
    if (!parsed || parsed <= 0) return;
    const { ingredients, stockLevels, transactions } = get();
    const ingredient = ingredients.find((i) => i.id === ingredientId);
    const outletStock = { ...(stockLevels[outletId] || {}) };
    outletStock[ingredientId] = (outletStock[ingredientId] || 0) + parsed;
    set({
      stockLevels: { ...stockLevels, [outletId]: outletStock },
      transactions: [{
        id: txnId(), date: new Date().toISOString(), type: 'stock_in', reason,
        ingredientId, outletId, qty: parsed, note, poRef,
        balance: outletStock[ingredientId], costPerUnit: ingredient?.costPerUnit || 0,
      }, ...transactions],
    });
  },

  // Bulk Stock In — multiple ingredients in one batch
  addBulkStockIn: (items, outletId, poRef = null) => {
    const { ingredients, stockLevels, transactions } = get();
    const newOutletStock = { ...(stockLevels[outletId] || {}) };
    const newTxns = [];

    items.forEach(({ ingredientId, qty, note, reason }) => {
      const parsed = parseFloat(qty);
      if (!parsed || parsed <= 0) return;
      const ingredient = ingredients.find((i) => i.id === ingredientId);
      newOutletStock[ingredientId] = (newOutletStock[ingredientId] || 0) + parsed;
      newTxns.push({
        id: txnId(), date: new Date().toISOString(), type: 'stock_in',
        reason: reason || 'purchase', ingredientId, outletId,
        qty: parsed, note: note || 'Bulk stock in', poRef,
        balance: newOutletStock[ingredientId], costPerUnit: ingredient?.costPerUnit || 0,
      });
    });

    set({
      stockLevels: { ...stockLevels, [outletId]: newOutletStock },
      transactions: [...newTxns, ...transactions],
    });
  },

  // Stock Out with Reason — auto triggers PO if below minStock
  addStockOut: (ingredientId, qty, outletId, note = '', reason = 'consumption') => {
    const parsed = parseFloat(qty);
    if (!parsed || parsed <= 0) return;
    const { ingredients, stockLevels, transactions, purchaseOrders } = get();
    const ingredient = ingredients.find((i) => i.id === ingredientId);
    const outletStock = { ...(stockLevels[outletId] || {}) };
    const current = outletStock[ingredientId] || 0;
    outletStock[ingredientId] = Math.max(0, current - parsed);
    const newBalance = outletStock[ingredientId];

    const newTxn = {
      id: txnId(), date: new Date().toISOString(), type: 'stock_out', reason,
      ingredientId, outletId, qty: parsed, note, poRef: null,
      balance: newBalance, costPerUnit: ingredient?.costPerUnit || 0,
    };

    // Auto-generate PO if stock drops below minStock
    let newPOs = purchaseOrders;
    const alreadyHasPendingPO = purchaseOrders.some(
      (p) => p.outletId === outletId &&
             p.items.some((item) => item.ingredientId === ingredientId) &&
             (p.status === 'Pending' || p.status === 'Ordered')
    );
    let autoPOGenerated = null;
    if (ingredient && newBalance < ingredient.minStock && !alreadyHasPendingPO) {
      const newPO = {
        id: poId(),
        date: new Date().toISOString(),
        outletId,
        vendorId: ingredient.vendorId || null,
        status: 'Pending',
        isAutoGenerated: true,
        items: [{ ingredientId, qty: ingredient.reorderQty || ingredient.minStock * 2, costPerUnit: ingredient.costPerUnit }],
        totalCost: (ingredient.reorderQty || ingredient.minStock * 2) * ingredient.costPerUnit,
      };
      newPOs = [newPO, ...purchaseOrders];
      autoPOGenerated = newPO.id;
    }

    set({
      stockLevels: { ...stockLevels, [outletId]: outletStock },
      transactions: [newTxn, ...transactions],
      purchaseOrders: newPOs,
      lastAutoPO: autoPOGenerated,
    });
  },

  lastAutoPO: null,
  clearLastAutoPO: () => set({ lastAutoPO: null }),

  // ── Transactions (Ledger) ─────────────────────────────────
  transactions: initialTransactions,

  // Daily report: opening balance, in, out, closing per ingredient
  getDailyReport: (date, outletId) => {
    const { transactions, ingredients, getStock } = get();
    const targetDate = new Date(date).toDateString();

    return ingredients.map((ing) => {
      const dayTxns = transactions.filter((t) => {
        const tDate = new Date(t.date).toDateString();
        return tDate === targetDate &&
          t.ingredientId === ing.id &&
          (outletId === 'all' || t.outletId === outletId);
      });

      const totalIn  = dayTxns.filter((t) => t.type === 'stock_in').reduce((s, t)  => s + t.qty, 0);
      const totalOut = dayTxns.filter((t) => t.type === 'stock_out').reduce((s, t) => s + t.qty, 0);
      const currentStock = (getStock(outletId))[ing.id] ?? 0;
      const openingBalance = currentStock + totalOut - totalIn;

      return {
        ingredient: ing,
        openingBalance: Math.max(0, openingBalance),
        totalIn,
        totalOut,
        closingBalance: currentStock,
        wastage: dayTxns.filter((t) => t.reason === 'wastage' || t.reason === 'damage').reduce((s, t) => s + t.qty, 0),
      };
    });
  },

  // Wastage summary
  getWastageSummary: (outletId) => {
    const { transactions, ingredients } = get();
    return transactions
      .filter((t) => (t.reason === 'wastage' || t.reason === 'damage') &&
                     (outletId === 'all' || t.outletId === outletId))
      .map((t) => {
        const ing = ingredients.find((i) => i.id === t.ingredientId);
        return { ...t, ingredientName: ing?.name, unit: ing?.unit, lossValue: t.qty * t.costPerUnit };
      });
  },

  // Stock valuation (weighted average)
  getStockValuation: (outletId) => {
    const { ingredients, getStock } = get();
    const stock = getStock(outletId);
    return ingredients.map((ing) => ({
      ingredient: ing,
      currentQty: stock[ing.id] ?? 0,
      value: (stock[ing.id] ?? 0) * ing.costPerUnit,
    }));
  },

  // ── Purchase Orders ───────────────────────────────────────
  purchaseOrders: initialPOs,
  addPurchaseOrder: (data) => set((s) => ({
    purchaseOrders: [{ id: poId(), date: new Date().toISOString(), status: 'Pending', isAutoGenerated: false, ...data }, ...s.purchaseOrders]
  })),
  updatePOStatus: (id, status) => set((s) => ({
    purchaseOrders: s.purchaseOrders.map((p) => p.id === id ? { ...p, status } : p)
  })),
}));
